# Generated by Django 4.1 on 2022-09-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer_utils', '0002_enginemanufacturer_transmissionmanufacturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EngineManufacturer',
        ),
        migrations.DeleteModel(
            name='TransmissionManufacturer',
        ),
    ]
