# Generated by Django 4.1 on 2022-09-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer_utils', '0003_delete_enginemanufacturer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailercategory',
            options={'verbose_name_plural': 'Trailer categories'},
        ),
    ]
