# Generated by Django 4.1 on 2022-09-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_alter_truck_state_dot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissionManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TruckPowertrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(blank=True, max_length=256, null=True)),
                ('transmission_type', models.CharField(blank=True, max_length=256, null=True)),
                ('number_of_speeds', models.PositiveIntegerField(blank=True, null=True)),
                ('overdrive', models.CharField(blank=True, max_length=256, null=True)),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('transmission_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.transmissionmanufacturer')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckInterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_side', models.CharField(blank=True, max_length=256, null=True)),
                ('power_steering', models.CharField(blank=True, max_length=256, null=True)),
                ('tilt_telescope', models.CharField(blank=True, max_length=256, null=True)),
                ('air_conditioning', models.CharField(blank=True, max_length=256, null=True)),
                ('air_conditioning_condition', models.CharField(blank=True, max_length=256, null=True)),
                ('cruise_control', models.CharField(blank=True, max_length=256, null=True)),
                ('power_locks', models.CharField(blank=True, max_length=256, null=True)),
                ('sleeper', models.CharField(blank=True, max_length=256, null=True)),
                ('sleeper_size', models.PositiveIntegerField(blank=True, max_length=256, null=True)),
                ('number_of_beds', models.PositiveIntegerField(blank=True, max_length=256, null=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckExterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab', models.CharField(blank=True, max_length=256, null=True)),
                ('doors', models.CharField(blank=True, max_length=256, null=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_displacement', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fuel_type', models.CharField(blank=True, max_length=256, null=True)),
                ('engine_model', models.CharField(blank=True, max_length=256, null=True)),
                ('engine_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.enginemanufacturer')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckChassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive', models.CharField(blank=True, max_length=256, null=True)),
                ('number_of_rear_axles', models.CharField(blank=True, max_length=256, null=True)),
                ('suspension', models.CharField(blank=True, max_length=256, null=True)),
                ('color', models.CharField(blank=True, max_length=256, null=True)),
                ('wheels', models.CharField(blank=True, max_length=256, null=True)),
                ('wheelbase', models.PositiveIntegerField(blank=True, null=True)),
                ('gvwr', models.CharField(blank=True, max_length=256, null=True)),
                ('gvw', models.PositiveIntegerField(blank=True, null=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckCategorySpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_and_gate', models.CharField(blank=True, max_length=256, null=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckCapacities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apu', models.CharField(blank=True, max_length=256, null=True)),
                ('apu_type', models.CharField(blank=True, max_length=256, null=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
    ]
