# Generated by Django 4.1 on 2022-09-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0004_enginemanufacturer_transmissionmanufacturer'),
        ('truck', '0006_remove_truckengine_engine_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckengine',
            name='engine_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck_utils.enginemanufacturer'),
        ),
        migrations.AddField(
            model_name='truckpowertrain',
            name='transmission_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck_utils.transmissionmanufacturer'),
        ),
    ]
