# Generated by Django 4.1 on 2022-09-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0008_alter_truckattachments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckattachments',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='truckcapacities',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='truckcategoryspecific',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='truckchassis',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_chassis', to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='truckdimensions',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='truckengine',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_engine', to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='truckexterior',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='truckimages',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_images', to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='truckinterior',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_interior', to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='truckpowertrain',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_powertrain', to='truck.truck'),
        ),
    ]
