# Generated by Django 4.1 on 2022-09-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0011_truck_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckengine',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
