# Generated by Django 4.1 on 2022-09-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0007_alter_truckcategory_parent'),
        ('truck', '0012_truckengine_horsepower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ('manufacturer', 'model', 'year', 'price')},
        ),
        migrations.AlterField(
            model_name='truck',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_trucks', to='truck_utils.truckcategory'),
        ),
    ]
