# Generated by Django 4.1 on 2022-09-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0007_alter_truckcategory_parent'),
        ('truck', '0016_alter_truckengine_engine_displacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckengine',
            name='engine_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='truck_utils.enginemanufacturer'),
        ),
    ]
