# Generated by Django 4.1 on 2022-09-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0018_alter_truckengine_engine_manufacturer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TruckImages',
            new_name='TruckImage',
        ),
    ]
