# Generated by Django 4.1 on 2022-09-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0019_rename_truckimages_truckimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckimage',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_images', to='truck.truck'),
        ),
    ]
