# Generated by Django 4.1 on 2022-09-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0008_country_state_city'),
        ('truck', '0020_alter_truckimage_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck_utils.city'),
        ),
        migrations.AddField(
            model_name='truck',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck_utils.country'),
        ),
        migrations.AddField(
            model_name='truck',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck_utils.state'),
        ),
    ]
