# Generated by Django 4.1 on 2022-09-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0008_country_state_city'),
        ('truck', '0021_truck_city_truck_country_truck_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_trucks', to='truck_utils.city'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_trucks', to='truck_utils.country'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_trucks', to='truck_utils.state'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='stock_number',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
