# Generated by Django 4.1 on 2022-09-06 06:31

from django.db import migrations, models
import truck.models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0022_alter_truck_city_alter_truck_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckchassis',
            name='gvw',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[truck.models.validate_comma]),
        ),
    ]
