# Generated by Django 4.1 on 2022-09-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0024_alter_truckchassis_gvw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
