# Generated by Django 4.1 on 2022-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0025_alter_truck_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='truck-videos'),
        ),
    ]
