# Generated by Django 4.1 on 2022-09-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0026_truckimage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckcategoryspecific',
            name='collision_mitigation_system',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
