# Generated by Django 4.1 on 2022-09-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0003_trailerinterior_treshold_plate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailerchassis',
            options={'verbose_name_plural': 'Trailer chassis'},
        ),
        migrations.AlterModelOptions(
            name='trailerdimensions',
            options={'verbose_name_plural': 'Trailer dimensions'},
        ),
    ]
