# Generated by Django 4.1 on 2022-09-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0004_alter_trailerchassis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailercategoryspecific',
            name='tariler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer'),
        ),
        migrations.AlterField(
            model_name='trailerchassis',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer'),
        ),
        migrations.AlterField(
            model_name='trailerdimensions',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer'),
        ),
        migrations.AlterField(
            model_name='trailerexterior',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer'),
        ),
        migrations.AlterField(
            model_name='trailerinterior',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer'),
        ),
    ]
