# Generated by Django 4.1 on 2022-09-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0006_alter_trailercategoryspecific_tariler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='stock_number',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
