# Generated by Django 4.1 on 2022-09-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0007_alter_trailer_stock_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ('manufacturer', 'model', 'year', 'price')},
        ),
    ]
