# Generated by Django 4.1 on 2022-09-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0009_alter_trailer_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerchassis',
            name='tires',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
