# Generated by Django 4.1 on 2022-09-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0008_country_state_city'),
        ('trailer', '0010_alter_trailerchassis_tires'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='listing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck_utils.listingtype'),
        ),
    ]
