# Generated by Django 4.1 on 2022-09-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0008_country_state_city'),
        ('trailer_utils', '0004_alter_trailercategory_options'),
        ('trailer', '0011_trailer_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_trailers', to='truck_utils.country'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_trailers', to='trailer_utils.trailercategory'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condtion_trailers', to='truck_utils.condition'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='listing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_type_trailers', to='truck_utils.listingtype'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_trailers', to='trailer_utils.trailermanufacturer'),
        ),
    ]
