# Generated by Django 4.1 on 2022-09-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0008_country_state_city'),
        ('trailer', '0012_trailer_country_alter_trailer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_trailers', to='truck_utils.condition'),
        ),
    ]
