# Generated by Django 4.1 on 2022-09-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0008_country_state_city'),
        ('trailer', '0013_alter_trailer_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_trailers', to='truck_utils.city'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_trailers', to='truck_utils.state'),
        ),
    ]
