# Generated by Django 4.1 on 2022-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0014_trailer_city_trailer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerdimensions',
            name='height',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
