# Generated by Django 4.1 on 2022-09-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0016_trailercategoryspecific_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailercategoryspecific',
            name='logistic_post_spacing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
