# Generated by Django 4.1 on 2022-09-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0018_trailerimage_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailerimage',
            options={'ordering': ('-image',)},
        ),
    ]
