# Generated by Django 4.1 on 2022-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0019_alter_trailerimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerimage',
            name='image',
            field=models.ImageField(null=True, upload_to='trailer-images/'),
        ),
    ]
