# Generated by Django 4.1 on 2022-09-08 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='mail',
            name='postal_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4,6}$', 'Invalid postal code')]),
        ),
    ]
