# Generated by Django 4.1 on 2022-09-08 09:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0025_alter_truck_vin'),
        ('trailer', '0017_trailercategoryspecific_logistic_post_spacing'),
        ('mail', '0003_truckmail_truckoffer_delete_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TruckFriendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrailerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('postal_code', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4,6}$', 'Invalid postal code')])),
                ('offer_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=64)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrailerMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('postal_code', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4,6}$', 'Invalid postal code')])),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrailerFriendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
