# Generated by Django 4.1 on 2022-09-09 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0017_trailercategoryspecific_logistic_post_spacing'),
        ('truck', '0025_alter_truck_vin'),
        ('mail', '0006_truckvideomail'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckvideomail',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='truck.truck'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrailerVideoMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('postal_code', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4,6}$', 'Invalid postal code')])),
                ('video_chat_service', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
