# Generated by Django 4.1 on 2022-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_truckvideomail_truck_trailervideomail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckvideomail',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='truckvideomail',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
