# Generated by Django 4.1 on 2022-09-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_alter_trailervideomail_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailervideomail',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trailervideomail',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
