# Generated by Django 4.1 on 2022-09-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_alter_trailervideomail_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('country', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
