# Generated by Django 4.1 on 2022-09-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_alter_truck_state_dot'),
        ('truck_utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
