# Generated by Django 4.1 on 2022-09-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0002_delete_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EngineManufacturer',
        ),
        migrations.DeleteModel(
            name='TransmissionManufacturer',
        ),
    ]
