# Generated by Django 4.1 on 2022-09-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0004_enginemanufacturer_transmissionmanufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truckcategory',
            options={'verbose_name_plural': 'Truck categories'},
        ),
    ]
