# Generated by Django 4.1 on 2022-09-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_utils', '0006_listingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='truck_utils.truckcategory'),
        ),
    ]
